select * from customer limit 10

--what is the total revenue generated by male vs female customers
select gender , sum(purchase_amount) as revenue
from customer
group by gender

--which customers used a discount but still spent more than average of purchase amount
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--which are the top 5 products with the highest average review rating
select item_purchased , round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Compare the average purchase amounts between Standard and Express Shipping.
 select shipping_type,avg(purchase_amount) as "AVG Revenue"
 from customer
 where shipping_type in ('Standard','Express')
 group by shipping_type

 ---compare average spend and total revenue between subscripers and non-subscribers
 select subscription_status,
 count(customer_id) as "Total Customers",
 round(avg(purchase_amount),2) as average_spend,
 round(sum(purchase_amount),2) as total_revenue
 from customer
 group by subscription_status
 order by total_revenue , average_spend desc

----which 5 products have the highest percentage of purchases with discount apllied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

----segment customers into new,returned and loyal based on their total number 
--previous purchases , and show the count of each segment
with customer_type as (
	select customer_id,previous_purchases,
	Case
		when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returned'
		else 'Loyal'
		end as customer_segment
	from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

------What are the top 3 most purchased product in each category
with item_counts as(
	select category,
		   item_purchased,
		   count(customer_id) as total_orders,
		   row_number() over (partition by category order by count(customer_id) desc ) as item_rank
	from customer
	group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3

---what is the total count of repeated buyers(with more than 5 previous purchases ) with subscriped or not

select subscription_status,
	   count(customer_id) as repeated_buyers
from customer
where previous_purchases > 5
group by subscription_status

---what is the revenue contributionof each age group
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc


 select * from customer limit 2
